version: '3.9'

services:
  main:
    container_name: express-credit-bot-server
    build:
      context: .
      dockerfile: ./Dockerfile.server 
    environment:
      - APP_PORT
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules   
    ports:
      - $APP_PORT:$APP_PORT
    depends_on:
      - postgres
    networks:
      - express-credit-bot-net
    restart: always
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - $DB_PORT:$DB_PORT  
    networks:
      - express-credit-bot-net 
    restart: always

volumes:
  pgdata:

networks:
  express-credit-bot-net:
    name: express-credit-bot-net
    driver: bridge